Add dummy tests to Expose OOM error
This commit is just to expose failures noticed in the merge of
stable-3.3 to master[1].

It seems that those failures have nothing to do with the merge itself,
but just with the fact that *new* tests have been added.

Just adding some dummy tests is enough to make the server_cache tests
fail with:

Exception: java.lang.OutOfMemoryError thrown from the
UncaughtExceptionHandler in thread "Timer-0"
Exception: java.lang.OutOfMemoryError thrown from the
UncaughtExceptionHandler in thread "groups NRT"
Exception: java.lang.OutOfMemoryError thrown from the
UncaughtExceptionHandler in thread "accounts NRT"

Running the MigrateH2CacheIT tests only produces no failures.

[1]https://gerrit-review.googlesource.com/c/modules/cache-chroniclemap/+/308947

Change-Id: I3175ba11e625517c959e9712d741edc53ba053d1